species: rhesus-monkey
receptorOrLocusType: IG
inputType: inline
sequences: |
  >IGHV1-AAU-U*01
  CAGGTCCAGCTGGTGCAGTCCGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTT
  TCCTGCAAGGCTTCTGGATTCACCTTCGGCAGCTATGCTATCAGCTGGGTGCGACAGGCC
  CCTGGACAAGGGCTTGAGTGGATGGGAGTGATCATCCCTCTTGTTGGTATAACAAACTAC
  GCAGAGAAGTTCCAGGGCAGAGTCACGATTACCGCGGACACGTCCACAAGCACAGCCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCCGTGTATTACTGTGCGAGAGG
  >IGHV1-AAU-U*02
  CAGGTCCAGCTGGTGCAGTCCGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGCTC
  TCCTGCAAGGCTTCTGGATACACCTTCAGCATCTATGCCATCAGTTGGGTGCGACAGGCC
  CCTGGACAAGGGCTTGAGTGGATGGGAGGGATCATCCCTCTTGTTGGTATAACAAACTAC
  GCACAGAAGTTCCAGGGCAGAGTCACGATTACCGCGGACACGTCCACAAGCACAGCCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCCGTGTATTACTGTGCGAG
  >IGHV1-AAU-U*03
  GAGGTCCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTC
  TCCTGCAAAGCTTCTGGATACATTTTCACCAGTTATGTTATCAGCTGGCTGCGACAGGCC
  CCTGGACAAGGGTTTGAGTGGATGGGAGGAATCCACCCTGGTTATGGTAGCACAAGCTAC
  GCACAGAAGTTCCAGGGCAGAGTCACGATTACCGCGGACATGTCCACGAGCACAGTCTAC
  ATGGAGCTGAGCAGTCTGAGATCTGAGGACATGGCCGTGTATTACTGTGCAGCAGA
  >IGHV1-ABW-S*01
  GAGGTCCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCCGTGAAAATC
  TCCTGCAAGGCTTCTGGATACACCTTCACCGACCACTACCTGAACTGGGTGCGACAGGCT
  CCTGGAAAAGGGCTTGAGTGGATGGGAGGTGTTGATCCTGAAGATGGTGAAGCAGACTAC
  GCACAGAAGTTCCAGGACAGAGTCACCATCACCGCGGACATGTCTACAGACACAGCCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCCGTGTATTACTGTGCAAGAGA
  >IGHV1-AEP*01
  CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGATTAAGCAGCCTGGGGCCTCAGTGAAGCTC
  TCCTGCAAGGCTTCTGGATATACCTTCACTAGCTACTACATGCACTGGGTGAGACAGGCC
  CCTGGACAAGGCCTTGAGTGGATAGGACTGATCTCCCCTTACAATGGTAACAAAGGCTAC
  GCACAGAACTTCCAGGGCAGAGTCACCATAACTACGGACACGTCCACGAGCACAGGCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACAGCCGTGTATTACTGTACGAGAGA
  >IGHV1-AEP*02
  CAGGTGCAGCTGGTGCAGTCTGGGGGTGAGATTAAGCAGCCTGGGGCCTCAGTGAAGCTC
  TCCTGCAAGGCTTCTGGATATACCTTCACTAGCTACTACATGCACTGGGTGAGACAGGCC
  CCTGGACAAGGCCTTGAGTGGATAGGACTGATCTCCCCTTACAATGGTAACAAAGGCTAC
  GCACAGAACTTCCAGGGCAGAGTCACCATAACTACGGACACGTCCACGAGCACAGGCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACAGCCGTGTATTACTGTACGAGAGA
  >IGHV1-AFG-S*01
  CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGATCCTCAGTGAAGGTC
  TCCTGCAAGGCTTCCGGATACACCTTCACTGACTACTACATGCACTGGGTGCGACAGGCC
  CCTGGACAAGGGCTTGAGTGGATGGGAGAAATCAACCCAAAAACTGGTGGCACAAACTAT
  GCACAGAAGTTCCAGGGCAGAGTCACCACGACCAGAGACACATCGACGAGCACAGCCTAC
  ATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCCGTGTATTACTGTGAGAGAGA
