version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  # an attempt at a package-build job specifically
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: python3 -m pip install --upgrade build
          name: Install PyPA's build tool
      - python/save-cache
      - run:
          command: python -m build
          name: Build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: python -m unittest
          name: Test
      - run:
          command: python -m vquest -h
          name: Try CLI
      - run:
          command: pip install /tmp/workspace/dist/*.whl
          name: Install from whl

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
